// <auto-generated />
using LojaProdutos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LojaProdutos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250406002727_AdicionandoBanco")]
    partial class AdicionandoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");
#pragma warning restore 612, 618
        }
    }
}
